name: Create Release

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create_release:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure the workflow has write permissions to the repository contents

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Get current version
        id: get_version
        run: echo "::set-output name=version::$(jq -r .version system.json)"

      - name: Get pull request details
        if: github.event_name == 'pull_request'
        id: pr_details
        run: |
          echo "::set-output name=pr_title::${{ github.event.pull_request.title }}"
          echo "::set-output name=pr_body::${{ github.event.pull_request.body }}"
          echo "::set-output name=pr_number::${{ github.event.pull_request.number }}"

      - name: Create zip file
        run: zip -r cain.zip .

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: v${{ steps.get_version.outputs.version }}
          name: Release ${{ steps.get_version.outputs.version }}
          body: |
            ## Changes in this release
            - Pull Request #${{ steps.pr_details.outputs.pr_number }}: ${{ steps.pr_details.outputs.pr_title }}
            - ${{ steps.pr_details.outputs.pr_body }}
          generateReleaseNotes: true
          makeLatest: true
          artifacts: perfectdraw.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true
